cmd/init.go, cmd/jsonschema_test.go, cmd/root.go, cmd/root_test.go, cmd/run_test.go, cmd/sample_test.go, cmd/server.go, cmd/server_test.go, cmd/service.go, cmd/service_test.go, go.mod, go.sum, main.go, pkg/runner/simple.go, pkg/runner/simple_test.go, sample/manifest.yaml
The following command will install atest as a Linux service. `atest service --action install`.
Set the default service port to be 7070 to avoid confliction
=> feat: add a service commnd

pkg/runner/simple.go
fix: reduce RunTestCase method cognitive complexity
=> fix: reduce cognitive complexity

.github/workflows/build.yaml
See also https://github.com/LinuxSuRen/api-testing/pull/60#pullrequestreview-1414391415
=> chore: skip the test report when owner is not linuxsuren

pkg/server/remote_server_test.go
Define a constant instead of duplicating this literal "Bearer {{.login.data.access_token}}" 3 times.
=> fix: Define a constant 

README.md, cmd/root_test.go, cmd/run.go, pkg/runner/expr_function.go, pkg/runner/expr_function_test.go, pkg/runner/simple.go, pkg/runner/simple_test.go, pkg/testing/case.go, pkg/testing/parser_test.go, sample/api-testing-schema.json, sample/testsuite-gitee.yaml, sample/testsuite-gitlab.yaml
fix https://github.com/LinuxSuRen/api-testing/issues/68
sample usage:
```
after:
items:
- "sleep(1)"
```
=> feat: support running before and after jobs with API request

cmd/run.go, cmd/run_test.go
fix https://github.com/LinuxSuRen/api-testing/issues/73
=> feat: support saving markdown report to a file

cmd/data/linux_service.txt, cmd/data/macos_service.xml, cmd/service.go, cmd/service_test.go
fix https://github.com/LinuxSuRen/api-testing/issues/53
=> feat: support to install service on macos

README.md, cmd/function.go, cmd/run.go, cmd/run_test.go, pkg/apispec/swagger.go, pkg/apispec/swagger_test.go, pkg/apispec/testdata/swagger.json, pkg/runner/simple.go, pkg/runner/writer_html.go, pkg/runner/writer_html_test.go, pkg/runner/writer_markdown.go, pkg/runner/writer_markdown_test.go, pkg/runner/writer_std.go, pkg/runner/writer_std_test.go, pkg/util/expand.go, pkg/util/expand_test.go
There are two important features in this PR. Now it could support brace expansion, and calculate the API coverage via Swagger:
```shell
atest run -p 'docs/api-testing/test-suite-{vm,resource}.yaml' --swagger-url http://172.11.0.13:32535/apidocs.json
```
=> feat: support to calculate the API coverage

pkg/runner/data/html.html, pkg/runner/testdata/report.html
Add some css to html.html, look like this:
=> feat: add some css to the HTML format report

console/atest-ui/src/views/TestCase.vue, go.mod, go.sum, pkg/runner/http.go, pkg/runner/http_test.go
=> feat: support providing the suggested body fields

Makefile, console/atest-ui/package-lock.json, console/atest-ui/package.json, console/atest-ui/src/App.vue, console/atest-ui/src/i18n.ts, console/atest-ui/src/locales/en.json, console/atest-ui/src/locales/zh.json, console/atest-ui/src/main.ts, console/atest-ui/src/views/TemplateFunctions.vue, console/atest-ui/src/views/TestCase.vue, console/atest-ui/src/views/TestSuite.vue
It will switch the language base on the browser setting.
See the screenshot
=> feat: add i18n support for the web ui

.github/testing/core.yaml, .github/workflows/build.yaml, pkg/runner/grpc.go
fix Got error when running the sample grpc testsuite file #200
Signed-off-by: Ink33 <Ink33@smlk.org>
=> fix: missing return in invokeRequest for stream rpc

cmd/function.go, cmd/function_test.go, docs/README.md, pkg/runner/expr_function.go, pkg/runner/expr_function_test.go, pkg/runner/grpc.go, pkg/runner/http.go, pkg/runner/http_test.go, pkg/testing/parser_test.go, sample/testsuite-gitlab.yaml
=> feat: add an expr function httpReady

console/atest-ui/src/locales/en.json, console/atest-ui/src/views/TestCase.vue, console/atest-ui/src/views/cache.ts, pkg/testing/remote/grpc_store.go
=> feat: support show the human-readable http status code on ui

console/atest-ui/src/locales/en.json, console/atest-ui/src/views/TestCase.vue, pkg/generator/curl_generator.go, pkg/generator/curl_generator_test.go, pkg/generator/data/curl.tpl, pkg/server/remote_server_test.go, pkg/testing/case.go, pkg/testing/case_test.go
=> feat: support to generate curl command

pkg/runner/grpc.go, pkg/runner/grpc_test.go
fix always pass when verify grpc expect body
=> fix: verify grpc expect body

.github/workflows/build.yaml, .github/workflows/release.yaml, .gitignore, Makefile, docs/README.md, docs/helm.md, helm/api-testing/.helmignore, helm/api-testing/Chart.yaml, helm/api-testing/templates/NOTES.txt, helm/api-testing/templates/_helpers.tpl, helm/api-testing/templates/deployment.yaml, helm/api-testing/templates/hpa.yaml, helm/api-testing/templates/ingress.yaml, helm/api-testing/templates/service.yaml, helm/api-testing/templates/serviceaccount.yaml, helm/api-testing/templates/tests/test-connection.yaml, helm/api-testing/values.yaml
=> feat: support releasing api-testing as a Helm chart

console/atest-ui/package.json, console/atest-ui/src/App.vue, console/atest-ui/src/main.ts, console/atest-ui/src/theme.ts, pkg/render/template.go, pkg/render/template_test.go, pkg/runner/grpc.go, pkg/runner/grpc_test.go, pkg/util/http.go, pkg/util/http_test.go
a cached client could reduce the network requests
=> feat: add local cached http client

.github/workflows/release.yaml, .gitpod.yml, console/atest-ui/src/App.vue, console/atest-ui/src/views/StoreManager.vue, console/atest-ui/src/views/TestCase.vue, console/atest-ui/src/views/TestSuite.vue, console/atest-ui/src/views/__test__/types.spec.ts, console/atest-ui/src/views/api.ts, console/atest-ui/src/views/cache.ts, console/atest-ui/src/views/net.ts, console/atest-ui/src/views/store.ts, console/atest-ui/src/views/types.ts, e2e/compose.yaml, e2e/entrypoint.sh, e2e/test-suite-common.yaml, pkg/server/remote_server.go, pkg/server/remote_server_test.go, pkg/version/constants.go, pkg/version/constants_test.go
fix https://github.com/LinuxSuRen/api-testing/issues/237
=> ui: reflect the network request related codes

.gitpod.yml
=> chore: put the api-testing extension into the gitpod config

pkg/generator/code_generator_test.go, pkg/generator/data/main.java.tpl, pkg/generator/java_generator.go, pkg/generator/testdata/expected_java_code.txt, pkg/generator/testdata/expected_java_cookie_request_code.txt, pkg/generator/testdata/expected_java_form_request_code.txt, pkg/server/remote_server_test.go
根据[golang_generator](https://github.com/LinuxSuRen/api-testing/blob/e05ff4b485e0c525ea7f78b4d653ddc230c5716e/pkg/generator/golang_generator.go)实现java_generator
#366
=> feat: support to generator Java code from a HTTP testCase

pkg/generator/data/main.go.tpl, pkg/generator/testdata/expected_go_code.txt, pkg/generator/testdata/expected_go_cookie_request_code.txt, pkg/generator/testdata/expected_go_form_request_code.txt
=> chore: add license header in the Go code generator

cmd/server.go, cmd/server_test.go, go.mod, pkg/mock/in_memory.go, pkg/mock/in_memory_test.go, pkg/mock/server.go, pkg/server/http.go, pkg/server/http_test.go
Usage: `atest server --mock-config api.yaml`
=> feat: support combine mock and core server together

pkg/generator/code_generator_test.go, pkg/generator/data/main.python.tpl, pkg/generator/python_generator.go, pkg/generator/testdata/expected_python_code.txt, pkg/generator/testdata/expected_python_cookie_request_code.txt, pkg/generator/testdata/expected_python_form_request_code.txt, pkg/server/remote_server_test.go
=> Support to generator Python code from a HTTP testCase #365

pkg/generator/code_generator_test.go, pkg/generator/data/main.javascript.tpl, pkg/generator/helper.go, pkg/generator/javascript_generator.go, pkg/generator/testdata/expected_javascript_body_request_code.txt, pkg/generator/testdata/expected_javascript_code.txt, pkg/generator/testdata/expected_javascript_cookie_request_code.txt, pkg/generator/testdata/expected_javascript_form_request_code.txt, pkg/server/remote_server_test.go
add javascript generator.
add javascript code generator test data.
feat: Support to generator JavaScript code from a HTTP testCase.
Fixes #395
=> feat: Support to generator JavaScript code from a HTTP testCase.

pkg/generator/importer.go, pkg/generator/importer_test.go, pkg/generator/testdata/expected_suite_from_sub_postman.yaml, pkg/generator/testdata/postman-sub.json
Fixes #101 
1.The original logic cannot convert sub folders beyond one Postman folder.
2.I can only convert the body in JSON format is raw.Therefore,I have modified the structure of the PostmanBody according to the document https://learning.postman.com/collection-format/advanced-concepts/request-definition/. Now, I need to convert it to test suite. Do I need to modify the code structure of test suite Request?
```Go
type RequestBody struct {
Value  string `json:"value" yaml:"value"`
isJson bool
}
```
=> fix: cannot import sub-collection of postman

cmd/mock.go, docs/api-testing-schema.json, docs/mock-server.md, docs/mock/image-registry.yaml, pkg/mock/in_memory.go, pkg/mock/in_memory_test.go, pkg/mock/testdata/api.yaml, pkg/mock/types.go, pkg/render/template.go, pkg/render/template_test.go, pkg/runner/http.go, pkg/runner/http_test.go, pkg/util/default.go
I complete parts of the docker registry server. Users can run `docker pull`, but I cannot fix the `filesystem layer verification problem`. Please let me know if you are familiar with it.
```shell
$ docker pull localhost:6060/linuxsuren/api-testing:master
master: Pulling from linuxsuren/api-testing
56c566a8d234: Verifying Checksum 
filesystem layer verification failed for digest sha256:56c566a8d234cbea1867522f63b812f51bb091866286e8f350f23a951171b9f5
```
I have read the [OCI Image Spec](https://github.com/opencontainers/image-spec/releases/tag/v1.1.0), but I still have no idea how to fix it. It looks like there are some problems on `Layer DiffID`.
Fixes #
=> feat: support image registry mock server

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING-ZH.md, CONTRIBUTING.md
=> chore: add docs style guide links

console/atest-ui/src/views/TestCase.vue
Fixes #461 
fix testcase pages show badge when badge value is 0.
=> fix: testcase pages show badge question

pkg/testing/loader_file.go, pkg/testing/parser_test.go
=> fix: the file path checking is incorrect on windows

helm/api-testing/templates/servicemonitor.yaml, helm/api-testing/values.yaml
Fixes #358 
Create a serviceMonitor in the helm chart to expose the Promethus metrics.
=> feat: add serviceMonitor in the helm chart

docs/site/content/zh/latest/releases/release-note-v0.0.17.md
We need to merge https://github.com/LinuxSuRen/api-testing/pull/481 before merging the current PR.
/cc @yuluo-yx
=> docs: add release note v0.0.17

pkg/runner/http.go, pkg/runner/http_test.go, pkg/runner/verify.go, pkg/runner/verify_test.go
>
See also [the article](https://symfonycasts.com/screencast/rest/application-problem) about `application/problem+json`.
I find the relevant problems originally comes from https://github.com/halo-dev/halo/pull/6097
Fixes #
=> feat: support JSON compaitble contentType parse

cmd/server_test.go, docs/api-testing-mock-schema.json, docs/constants.go, pkg/mock/in_memory_test.go, pkg/mock/reader.go, pkg/mock/types.go, pkg/testing/parser.go
Related to #498
Adds JSON schema for the mock type and updates the `types.go` file to include JSON struct tags.
- **JSON Schema Creation**: Adds a new file `docs/api-testing-mock-schema.json` that defines the JSON schema for the mock server. This schema includes definitions for objects, items, and webhooks, with detailed properties and required fields to accurately represent the structure and types defined in `pkg/mock/types.go`.
- **Code Update**: Updates the `pkg/mock/types.go` file by adding JSON struct tags to all fields, ensuring that each field is correctly annotated for both YAML and JSON serialization. This change aligns the codebase with the newly created JSON schema and facilitates the generation of accurate JSON representations of the mock types.
---
For more details, open the …
=> Add JSON schema for mock types

console/atest-ui/src/views/TestingPanel.vue
=> fix: the test suite tree cannot be selected

pkg/render/template.go, pkg/render/template_test.go
Related to #501
Adds the `rasEncryptWithPublicKey` function to the template rendering functionalities and includes unit tests for the new function.
- **New Functionality**: Implements the `rasEncryptWithPublicKey` function in `pkg/render/template.go`, allowing users to encrypt content with a public key directly within templates. This function takes two string arguments (content and key), performs RSA encryption, and returns the encrypted content in base64 encoded format.
- **Error Handling**: Adds error handling for key parsing and encryption processes within the `rasEncryptWithPublicKey` function to ensure robustness.
- **Unit Tests**: Extends `pkg/render/template_test.go` with tests for the `rasEncryptWithPublicKey` function, verifying its behavior with both valid and invalid keys, and …
=> Add RSA encryption function to templates

console/atest-ui/package-lock.json, console/atest-ui/package.json, console/atest-ui/src/locales/en.json, console/atest-ui/src/views/TestCase.vue, e2e/code-generator/start.sh, e2e/start.sh, tools/make/run.mk, tools/make/ui.mk
>
It will give the error tips if the JSON is invalid.
Fixes #
=> feat: add testCase page json lint

pkg/extension/option.go, pkg/extension/option_test.go
=> chore: remove the extension sock file before start

console/atest-ui/src/views/TestSuite.vue, console/atest-ui/src/views/TestingPanel.vue, console/atest-ui/src/views/net.ts, pkg/runner/http.go, pkg/runner/http_test.go, pkg/runner/testdata/swagger.json
=> feat: improve the test case creating process on ui

console/atest-ui/src/App.vue, console/atest-ui/src/views/StoreManager.vue, console/atest-ui/src/views/TestCase.vue, console/atest-ui/src/views/__test__/cache.spec.ts, console/atest-ui/src/views/__test__/store.spec.ts, console/atest-ui/src/views/__test__/types.spec.ts, console/atest-ui/src/views/cache.ts, console/atest-ui/src/views/net.ts, console/atest-ui/src/views/store.ts, console/atest-ui/src/views/types.ts
=> chore: improve the store manager ui

.github/workflows/build.yaml
=> chore: support to parse the front-end coverge

console/atest-ui/src/views/TestSuite.vue, console/atest-ui/src/views/net.ts, pkg/testing/loader_file.go, pkg/testing/loader_file_test.go
=> fix: overwrite test case when creating duplicated

cmd/extension.go, pkg/downloader/oci.go, pkg/downloader/store.go, pkg/server/store_ext_manager.go
add download extension store image prefix, default image prefix is linuxsuren.
=> feat: add download extension store image prefix

cmd/server.go, console/atest-ui/package-lock.json, console/atest-ui/src/views/TestCase.vue, console/atest-ui/src/views/types.ts, pkg/generator/curl_generator_test.go, pkg/mock/in_memory.go, pkg/mock/in_memory_test.go, pkg/runner/http.go, pkg/runner/http_test.go, pkg/runner/writer_http.go, pkg/server/remote_server.go, pkg/util/default.go
increase the body size limit default value to be 5120
>
@SamYSF I made some changes to the test case page. It can show the body size.
Fixes #
=> feat: support to show the body size on page

console/atest-ui/src/views/StoreManager.vue, console/atest-ui/src/views/TestCase.vue, console/atest-ui/src/views/store.ts, console/atest-ui/src/views/types.ts, pkg/runner/http.go, pkg/server/remote_server_test.go, pkg/testing/parser.go
=> feat: support embed file upload

Dockerfile, console/atest-ui/src/views/TestCase.vue, e2e/Dockerfile, e2e/test-suite-common.yaml, pkg/runner/http.go, pkg/runner/runner.go, pkg/server/remote_server.go, pkg/util/default.go, tools/make/run.mk
=> feat: support to get headers from binary request

console/atest-ui/src/views/TestCase.vue, pkg/runner/http.go, pkg/runner/runner.go, pkg/runner/runner_test.go, pkg/server/remote_server.go
=> fix: the filename is missing when downloading

docs/site/content/zh/latest/tasks/verify.md
=> docs: give more examples of the verify

docs/site/content/zh/latest/tasks/mock.md, pkg/mock/in_memory.go, pkg/mock/in_memory_test.go, pkg/mock/testdata/api.yaml
=> fix: mock body render missing context

console/atest-ui/src/views/DataManager.vue, docs/site/content/zh/latest/tasks/mock/simple.yaml, go.mod, go.sum, pkg/mock/in_memory.go, pkg/mock/types.go
=> feat: support proxy request body amend in mock

cmd/extension.go, cmd/server.go, console/atest-ui/src/views/TestSuite.vue, console/atest-ui/src/views/net.ts, console/atest-ui/src/views/types.ts, docs/site/content/zh/latest/tasks/extension.md, extensions/README.md, pkg/apispec/remote_swagger.go, pkg/apispec/swagger.go, pkg/downloader/extension.go, pkg/downloader/oci.go, pkg/server/store_ext_manager.go, pkg/util/home/common.go, pkg/util/home/common_test.go
=> support to load swaggers from an extension

console/atest-ui/src/components/HistoryInput.vue, console/atest-ui/src/views/DataManager.vue, console/atest-ui/src/views/TestSuite.vue
=> feat: support to refresh tables

console/atest-ui/src/views/DataManager.vue, console/atest-ui/src/views/__test__/store.spec.ts, console/atest-ui/src/views/net.ts, console/atest-ui/src/views/store.ts, extensions/README.md
>
close #655 
See also https://github.com/LinuxSuRen/atest-ext-store-cassandra/pull/1
=> feat: add cassandra database support

.github/workflows/license-check.yaml, console/atest-ui/src/views/DataManager.vue, console/atest-ui/src/views/__test__/store.spec.ts, console/atest-ui/src/views/__test__/types.spec.ts, console/atest-ui/src/views/store.ts
=> feat: add opengemini support

cmd/function.go, cmd/init.go, cmd/jsonschema.go, cmd/jsonschema_test.go, cmd/mock-compose.go, cmd/root.go, cmd/root_test.go, cmd/service.go, docs/site/content/zh/latest/tasks/mock.md, pkg/mock/in_memory.go, pkg/mock/reader.go, pkg/mock/types.go
=> feat: support to start compose mock proxy servers

console/atest-ui/src/views/DataManager.vue, e2e/code-generator/Dockerfile
=> feat: using code editor instead of input for sql editing

Dockerfile, cmd/convert_test.go, cmd/function_test.go, cmd/jsonschema_test.go, cmd/mock-compose.go, cmd/mock_test.go, cmd/root_test.go, cmd/sample_test.go, cmd/server_test.go, docs/site/content/zh/latest/tasks/mock.md, pkg/mock/in_memory.go, pkg/mock/types.go, pkg/runner/http_test.go, pkg/server/store_ext_manager_test.go, tools/github-actions/setup-deps/action.yml
=> add tcp proxy support

pkg/testing/loader_file.go, pkg/testing/loader_non.go
**Which issue(s) this PR fixes:**
Fixes #700 
Fix: Improve error reporting for unimplemented Query in loaders
**What this PR does / why we need it:**
This PR refactors the Query methods in pkg/testing/loader_file.go and pkg/testing/loader_non.go.
Previously, these methods did not clearly indicate their inability to perform database queries in a way that aligns with Go's error handling conventions:
fileLoader.Query returned a nil error while passing a "not support" message through the data payload.
nonLoader.Query returned a nil error and an empty result, failing silently.
These behaviors made it harder for calling code to reliably determine if a query was unsupported and could lead to confusion during debugging.
This change modifies both methods to return an …
=> Fix: (#700) Improve error reporting for Query in fileLoader and nonLoader.

console/atest-ui/src/views/WelcomePage.vue
>
Enhancement
Improving UI of welcome page
Fixes #
=> improving UI of welcome page

console/atest-ui/package-lock.json, console/atest-ui/package.json, console/atest-ui/src/assets/base.css, console/atest-ui/src/assets/main.css, console/atest-ui/src/locales/en.json, console/atest-ui/src/locales/zh.json, console/atest-ui/src/views/DataManager.vue, console/atest-ui/src/views/TestCase.vue
>
below is the autocompletion of the HTTP payload:
Fixes #
=> feat: support sql completion for table names

docs/site/content/zh/_index.md
=> chore: add a download link on the webpage

console/atest-ui/src/views/DataManager.vue, console/atest-ui/src/views/cache.ts, console/atest-ui/src/views/net.ts
=> chore: put data manager cache to sessionStorage

docs/site/content/zh/latest/tasks/mock.md, docs/site/content/zh/latest/tasks/mock/webhook-syslog.yaml, pkg/mock/in_memory.go, pkg/mock/types.go
=> chore: print error message when sending webhook failed

console/atest-ui/src/locales/en.json, console/atest-ui/src/locales/zh.json, console/atest-ui/src/views/MockManager.vue, docs/api-testing-mock-schema.json, docs/constants.go, pkg/server/remote_server.go
=> chore: improve the mock log output

console/atest-ui/src/views/DataManager.vue, console/atest-ui/src/views/StoreManager.vue, console/atest-ui/src/views/TestCase.vue, console/atest-ui/src/views/TestSuite.vue, console/atest-ui/src/views/magicKeys.ts
=> fix: key-bindings fail after compile

cmd/server.go, pkg/server/ai_interface.go, pkg/server/remote_server.go, pkg/testing/testdata/data/core/extension.yaml
This PR defines a standard communication interface for AI plugins within the existing unified plugin architecture. Instead of treating AI
plugins as special cases, they now use the same extension system as other plugins with category-based identification.
Key changes:
- Added `pkg/server/ai_interface.go` with standardized AIRequest/AIResponse structures
- Enhanced ExtManager with category-based plugin filtering capabilities
- Added categories field support to plugin configuration
- Follows simple design patterns similar to langchaingo (model + prompt)
The interface uses JSON message protocol over the existing plugin communication channels, maintaining consistency with the current
architecture while providing AI-specific data structures.
**Which …
=> feat: define AI plugin communication interface standard

cmd/testdata/stores.yaml, console/atest-desktop/forge.config.js, console/atest-ui/src/views/store.ts, sample/ai-extension.yaml
- Add AI extension configuration in sample/ai-extension.yaml
- Update testdata/stores.yaml to include AI plugin registration
- Register atest-ext-ai in UI store types (console/atest-ui/src/views/store.ts)
- Enable automatic download and startup via extension registry
This enables 'make run-server' to automatically build and connect AI plugin
without manual download of atest-ext-ai repository.
=> integrate atest-ext-ai plugin into auto-build process
