- sample/kubernetes.yaml
> chore: add more samples about how to use the HTTP request

- cmd/service.go
> Modify Command Service exec-start mode

- console/atest-ui/src/views/TestSuite.vue
- pkg/testing/loader_file.go
> fix: validation is missing on the testsuite creation UI

- .dockerignore
- Dockerfile
- Makefile
- README.md
- cmd/server.go
- docs/README.md
- sample/argocd/simple.yaml
- sample/kubernetes/kustomization.yaml
- sample/kubernetes/manifest.yaml
- chore: add argocd manifests
- fix the version issues
> chore: add argocd manifest files

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- pkg/util/default.go
- pkg/util/default_test.go
continue to fix https://github.com/LinuxSuRen/api-testing/pull/234
> fix: cannot get the correct value when have symbol ;

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- Makefile
- cmd/service.go
- go.sum
- go.work.sum
upstream https://github.com/LinuxSuRen/api-testing/pull/235
> fix: the helm app version is incorrect

- README.md
> docs: fix readme file link error

- .github/workflows/md-link-check.yml
- README.md
- checklink_config.json
> feat: add github action to check md link

- Dockerfile
> fix: upgrade the base image due the security issue

- CONTRIBUTION.md
考虑到本项目涉及到前后端部分，尤其是对于考虑参与[开源之夏](https://github.com/LinuxSuRen/api-testing/issues/345)议题的同学，建议至少完成以下的基础内容：
* [Go 入门教程](https://go.dev/doc/tutorial/getting-started)，例如：Go 官方教程，或者其他你喜欢的内容
* [Vue 入门教程](https://vuejs.org/guide/introduction.html)
* 本项目的源码编译、镜像构建、二进制以及容器的启动
* 挑选难度适宜的 issue 若干，或者解决在阅读源码时发现的任何问题（避免大量简单、重复的问题）
> docs: add a tech table for the beginner

- pkg/generator/code_generator_test.go
- pkg/generator/data/main.go.tpl
- pkg/generator/testdata/expected_go_code.txt
- pkg/generator/testdata/expected_go_cookie_request_code.txt
- Solved this issue: #360 . 
- Modifications to #361
> feat: add the cookie setting for golang code generator

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> chore: create a PR template

- .github/workflows/stale.yml
> chore: add stale bot

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> chore: update the PR template

- CONTRIBUTION-ZH.md
- CONTRIBUTION.md
> docs: update contribution docs

- go.mod
- pkg/mock/data/api.yaml
- pkg/mock/in_memory.go
- pkg/mock/in_memory_test.go
- pkg/mock/server.go
- pkg/mock/types.go
This feature allows users to have much more control over the mock server.
> feat: support detailed mock server

- .github/workflows/issue-comment.yml
> chore: add issue comment github actions

- README-ZH.md
- README.md
- For #373 
- Add community-related & add zh readme.
> chore: update readme & add community-related

- CODE_OF_CONDUCT.MD
> docs: add code of conduct docs

- .github/workflows/command.yml
> chore(ci): add pull request retest action

- cmd/server.go
- cmd/server_test.go
- pkg/runner/http.go
- pkg/runner/http_test.go
- pkg/server/remote_server_test.go
> fix: the status code not match error ignored

- package-lock.json
> chore: delete package-lock.json

- CONTRIBUTING-ZH.md
- CONTRIBUTING.md
- README-ZH.md
- README.md
> docs: add links between Chinese and English version

- pkg/mock/in_memory.go
- pkg/mock/in_memory_test.go
- pkg/mock/server.go
- pkg/mock/testdata/api.yaml
- pkg/mock/types.go
As mentioned in the title.
Fixes #
> fix: using a better header struct

- .github/workflows/release-drafter.yml
- .github/workflows/release.yaml
- For https://github.com/LinuxSuRen/api-testing/pull/414#issuecomment-2101818968
> ci: update release ci yml

- tools/make/env.mk
- tools/make/helm.mk
- tools/make/image.mk
- For https://github.com/LinuxSuRen/api-testing/pull/423#discussion_r1595057240
> fix: ci failure when specifying container registration address

- .github/workflows/release.yaml
> fix: remove the not found command: tree

- .github/workflows/release.yaml
> fix: the dir is incorrect for publishing desktop

- .github/workflows/release.yaml
- console/atest-desktop/forge.config.js
> chore: remove the prefix v in the version

- .github/workflows/release.yaml
> fix: missing the npm install during publish

- .github/workflows/release.yaml
> fix: using powershell on windows

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- go.work.sum
> chore: add macos-13 into the build matrix

- console/atest-desktop/README.md
- console/atest-desktop/forge.config.js
> fix: the win config is incorrect

- console/atest-ui/src/locales/en.json
- console/atest-ui/src/locales/zh.json
- console/atest-ui/src/views/TestSuite.vue
- console/atest-ui/src/views/net.ts
- pkg/server/remote_server.go
- pkg/server/remote_server_test.go
- pkg/server/server.pb.go
- pkg/server/server.pb.gw.go
- pkg/server/server.proto
- pkg/server/server.swagger.json
- pkg/server/server_grpc.pb.go
- pkg/testing/loader.go
- pkg/testing/loader_file.go
- pkg/testing/loader_file_test.go
- pkg/testing/loader_non.go
- pkg/testing/remote/grpc_store.go
fixes #393 
What this PR does / why we need it:
Support to view the YAML on the testSuite page.
> feat: support to view testSuite as YAML on web page

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- tools/make/desktop.mk
- tools/make/golang.mk
- tools/make/run.mk
- tools/make/ui.mk
> chore: cp atest to the desktop dir

- console/atest-ui/src/locales/en.json
- console/atest-ui/src/locales/zh.json
- console/atest-ui/src/views/TestSuite.vue
fixes #393 
1.Add view YAML full screen and cancel
2.Reformat the TestSuite page button
> feat: add view YAML full screen

- console/atest-desktop/main.js
> fix: error when opening atest-desktop on Windows

- .github/workflows/build.yaml
- .github/workflows/qodana_code_quality.yml
- console/atest-ui/src/views/TestCase.vue
- console/atest-ui/src/views/types.ts
- pkg/server/remote_server.go
- pkg/server/remote_server_test.go
> feat: support to return the body string even it is invalid

- .github/workflows/build.yaml
- .gitignore
- console/atest-desktop/api.js
- console/atest-desktop/api.test.js
- console/atest-desktop/forge.config.js
- console/atest-desktop/index.html
- console/atest-desktop/main.js
- console/atest-desktop/package-lock.json
- console/atest-desktop/package.json
- console/atest-desktop/preload.js
- console/atest-desktop/renderer.js
- tools/make/desktop.mk
> feat: improve the desktop system control features

- cmd/server.go
- cmd/server_test.go
- cmd/testdata/stores.yaml
- pkg/server/remote_server_test.go
> fix: avoid exit the main process when plugin start failed

- cmd/server.go
- cmd/server_test.go
- console/atest-desktop/main.js
- e2e/README.md
- pkg/mock/in_memory.go
- pkg/runner/http_test.go
- pkg/server/http.go
- pkg/server/remote_server_test.go
- pkg/util/net.go
> fix: not work when grpc port is a random one

- e2e/code-generator/start.sh
>
The code generating e2e tests will not fail even there are promlems.
Fixes #
> fix: missing the container exit code check

- .github/workflows/build.yaml
- pkg/downloader/oci.go
- pkg/downloader/oci_test.go
- pkg/downloader/store.go
- pkg/downloader/testdata/registry.yaml
>
Test output:
```shell
go run . extension git
found target file atest-store-git_windows_amd64_v1/atest-store-git.exe
downloaded atest-store-git.exe
```
Fixes #
> fix: cannot download oci artifact on windows

- docs/site/hugo.toml
> fix: try to change the site sub-path

- docs/site/hugo.toml
> docs: fix docs site zh show bug

- .github/CODEOWNERS
I add @yuluo-yx and @Ink-33 to the CODEOWNERS file. Please take a look at it.
> chore: add the codeOwners file

- .github/workflows/release.yaml
- pkg/server/data/headers.yaml
- pkg/server/remote_server.go
- pkg/server/remote_server_test.go
> chore: add more content-type headers

- console/atest-ui/src/views/TestCase.vue
- console/atest-ui/src/views/TestSuite.vue
- console/atest-ui/src/views/TestingPanel.vue
> ui: add colors for some texts and buttons

- console/atest-ui/src/views/TestCase.vue
- console/atest-ui/src/views/TestSuite.vue
- console/atest-ui/src/views/magicKeys.ts
> feat: add more shortcuts

- console/atest-ui/src/views/StoreManager.vue
- console/atest-ui/src/views/TemplateFunctions.vue
- console/atest-ui/src/views/TestCase.vue
> chore: add more magic keys on ui page

- console/atest-ui/src/views/TestingPanel.vue
- console/atest-ui/src/views/magicKeys.ts
> feat: support test case nav via shortcut

- e2e/test-suite-common.yaml
- go.mod
- pkg/extension/option.go
- pkg/runner/grpc.go
- pkg/server/remote_server.go
- pkg/testing/parser.go
> feat: enable refelction of the extension server

- pkg/runner/http.go
- pkg/runner/http_test.go
- pkg/runner/testdata/swagger.json
> fix: the suggested apis query is missing

- .github/workflows/docs.yaml
- pkg/mock/testdata/api.yaml
> publish api-testing mock server JSON schema

- console/atest-ui/src/views/TestSuite.vue
- console/atest-ui/src/views/store.ts
> fix: the new test case request is always empty

- console/atest-ui/src/views/SecretManager.vue
- console/atest-ui/src/views/StoreManager.vue
- console/atest-ui/src/views/TestCase.vue
- console/atest-ui/src/views/TestSuite.vue
- console/atest-ui/src/views/TestingPanel.vue
> fix: the ui loading function is not working

- console/atest-ui/src/views/TestCase.vue
> chore: support to close message tip

- README-ZH.md
- README.md
> chore: add project years badge

- docs/site/hugo.toml
> fix: the root path of docs is incorrect

- .github/release-drafter.yml
> fix the release note link in pr template

- Dockerfile
- cmd/run.go
- cmd/server.go
- console/atest-ui/src/views/TemplateFunctions.vue
- console/atest-ui/src/views/WelcomePage.vue
- console/atest-ui/src/views/net.ts
- console/atest-ui/ui.go
- docs/site/content/zh/latest/tasks/quickstart.md
- docs/site/content/zh/latest/tasks/verify.md
- e2e/test-suite-common.yaml
- go.mod
- go.sum
- go.work.sum
- main.go
- pkg/render/template.go
- pkg/render/template_test.go
- pkg/runner/http.go
- pkg/server/remote_server_test.go
- pkg/service/sbom.go
- pkg/util/http.go
- pkg/version/mod.go
- pkg/version/mod_test.go
- pkg/version/testdata/go.mod.txt
> support to run test case with filter

- cmd/run.go
- docs/site/content/zh/latest/tasks/code-generator.md
- e2e/code-generator/compose.yaml
- e2e/code-generator/robot-framework.sh
- e2e/code-generator/start.sh
- pkg/generator/code_generator.go
- pkg/generator/data/robot-suite.tpl
- pkg/generator/data/robot.tpl
- pkg/generator/python_generator.go
- pkg/generator/robot_generator.go
- pkg/generator/robot_generator_test.go
- pkg/generator/testdata/simple.robot
- pkg/generator/testdata/suite.robot
- pkg/generator/testdata/with-headers.robot
- pkg/server/remote_server.go
- pkg/server/remote_server_test.go
- tools/make/test.mk
> feat: support to generate robot-framework script

- .github/dependabot.yml
> chore: set package ecosystem of dependabot

- console/atest-ui/package-lock.json
- console/atest-ui/src/App.vue
- console/atest-ui/src/views/TestCase.vue
- console/atest-ui/src/views/TestingPanel.vue
- go.work.sum
> fix: the ui component binding errors

- console/atest-ui/src/locales/en.json
- pkg/testing/case.go
- pkg/testing/case_test.go
> test: add unit tests of binary upload

- cmd/run.go
- pkg/apispec/fake.go
- pkg/apispec/swagger.go
- pkg/runner/writer.go
- pkg/runner/writer_github_pr_comment.go
- pkg/runner/writer_github_pr_comment_test.go
- pkg/runner/writer_grpc.go
- pkg/runner/writer_html.go
- pkg/runner/writer_http.go
- pkg/runner/writer_json.go
- pkg/runner/writer_json_test.go
- pkg/runner/writer_markdown.go
- pkg/runner/writer_markdown_test.go
- pkg/runner/writer_pdf.go
- pkg/runner/writer_pdf_test.go
- pkg/runner/writer_std.go
- pkg/runner/writer_std_test.go
> chore: support to print test case count in stdout

- pkg/mock/in_memory.go
> fix: webhook auth should support go template

- console/atest-ui/src/views/DataManager.vue
> chore: let the sql query input be empty

- console/atest-ui/src/views/DataManager.vue
- console/atest-ui/src/views/__test__/store.spec.ts
- console/atest-ui/src/views/net.ts
- console/atest-ui/src/views/store.ts
- extensions/README.md
> feat: add elasticsearch extension support

- cmd/server.go
- pkg/server/store_ext_manager.go
> feat: support to start extension via http

- docs/package-lock.json
- docs/site/content/zh/latest/api/_index.md
- docs/site/content/zh/latest/install/_index.md
- docs/site/content/zh/latest/install/install-helm.md
- docs/site/content/zh/latest/install/install-local.md
> docs: improve the document site

- console/atest-ui/src/App.vue
- console/atest-ui/src/assets/main.css
- console/atest-ui/src/views/DataManager.vue
- console/atest-ui/src/views/TestCase.vue
> improve the table on the data manager ui

- console/atest-ui/src/views/DataManager.vue
> fix: redis query page issues

- console/atest-ui/src/views/DataManager.vue
> fix: cannot query data from orm

- console/atest-ui/src/assets/base.css
>
before 
her is After and before comparison
Fixes #
> fixed small UI bug of Dark theme

- pkg/server/remote_server.go
> feat: support to render the sql as template

- console/atest-ui/src/views/DataManager.vue
- console/atest-ui/src/views/TestCase.vue
- console/atest-ui/src/views/languageComplete.ts
> chore: support not show the native sql

- .github/release-drafter.yml
>
See also https://github.com/release-drafter/release-drafter?tab=readme-ov-file#exclude-contributors
Fixes #
> chore: exclude dependabot in the release draft

- .github/dependabot.yml
> chore: enable desktop-ui update in the dependabot.yml

- pkg/render/template.go
- pkg/render/template_test.go
> feat: add go template func: uptimeDate

- pkg/server/store_ext_manager.go
> fix: cannot start plugin on windows

- console/atest-desktop/preload.js
> feat: support opening in browser for desktop

- console/atest-ui/package.json
- console/atest-ui/src/views/DataManager.vue
> chore: using el-splitter on the data manager page
